project_id = "yusqctrtoskjtahtibwh"

[functions.daily-canvas-sync]
verify_jwt = false

[functions.auto-scheduler]
verify_jwt = false

[functions.scheduling-preview]
verify_jwt = false

[functions.administrative-tasks]
verify_jwt = false