project_id = "yusqctrtoskjtahtibwh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge_runtime]
enabled = true
port = 54327

[functions.auto-scheduler]
verify_jwt = false

[functions.scheduling-preview]
verify_jwt = false

[functions.daily-canvas-sync]
verify_jwt = false

[functions.administrative-tasks]
verify_jwt = false

[functions.migrate-administrative-tasks]
verify_jwt = false