// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yusqctrtoskjtahtibwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1c3FjdHJ0b3NranRhaHRpYndoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTU5NzEsImV4cCI6MjA2OTczMTk3MX0.fy6wBPoL24VdKKaG22IPlAe0-Zj8cKT1DcJa6yhtklc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: { schema: 'public' },
  auth: {
    storage: localStorage,
    persistSession: false,
    autoRefreshToken: false,
  }
});